### ISSUE TITLE
116 Error

### ISSUE THREAD

**Issue by DatOnePlayer** [pixaxeofpixie/Braindustry-Mod#10]
Beta 116 cannot load your mod

Lots of errors that I couldn't list or snapshot

**Comment by DatOnePlayer** [comment]
@pixaxeofpixie

**Comment by DatOnePlayer** [comment]
![Screenshot_20201124-124535_Mindustry](https://user-images.githubusercontent.com/61370548/100053713-2f8f0f00-2e53-11eb-9b92-c9f4fde89dc5.jpg)
![Screenshot_20201124-124538_Mindustry](https://user-images.githubusercontent.com/61370548/100053718-31f16900-2e53-11eb-8bc3-8788ad54f49c.jpg)
![Screenshot_20201124-124543_Mindustry](https://user-images.githubusercontent.com/61370548/100053721-33bb2c80-2e53-11eb-9d05-a54dfa2d9a00.jpg)
![Screenshot_20201124-124548_Mindustry](https://user-images.githubusercontent.com/61370548/100053723-34ec5980-2e53-11eb-903f-5635169c7183.jpg)
![Screenshot_20201124-124552_Mindustry](https://user-images.githubusercontent.com/61370548/100053728-374eb380-2e53-11eb-9d71-ff23581209a7.jpg)
![Screenshot_20201124-124557_Mindustry](https://user-images.githubusercontent.com/61370548/100053732-387fe080-2e53-11eb-8e8c-04181129f355.jpg)
![Screenshot_20201124-124603_Mindustry](https://user-images.githubusercontent.com/61370548/100053735-3ae23a80-2e53-11eb-9701-70f8ce85d3c0.jpg)
![Screenshot_20201124-124609_Mindustry](https://user-images.githubusercontent.com/61370548/100053742-3d449480-2e53-11eb-925b-d96377da4e8d.jpg)
![Uploading Screenshot_20201124-124614_Mindustry.jpg…]()

**Comment by DatOnePlayer** [comment]
![Screenshot_20201124-124624_Mindustry](https://user-images.githubusercontent.com/61370548/100053758-446ba280-2e53-11eb-9721-3679524a117c.jpg)

**Comment by pixaxeofpixie** [comment]
I know this problem,and solving it,but i dont have stability internet connection and i dont know wats mean "constructor",maybe anuken change this field in hjson-s.

**Comment by DatOnePlayer** [comment]
![Screenshot_20201124-150358_Mindustry](https://user-images.githubusercontent.com/61370548/100065553-7cc8ac00-2e66-11eb-8ad7-5ecb60d88efb.jpg)

Newest one after this mod update

**Comment by pixaxeofpixie** [comment]
Fix,im try on my 116 google play build,and all is ok.
