### ISSUE TITLE
I have several ideas

### ISSUE THREAD

**Issue by DatOnePlayer** [pixaxeofpixie/Braindustry-Mod#12]
If you like to hear it comment

**Comment by pixaxeofpixie** [comment]
Yes,give me your ideas.

**Comment by DatOnePlayer** [comment]
1. A melee unit (super close range)
2. Shotgun turret (accepts Scrap, Titanium Carbide and Thorium)
3. Crowd Control turret (One shot hits different targets, similar to frag, low damage but high rate of fire)

4. Another turret similar to Segment and Parallax

5. Maybe a new map and new resources

**Comment by pixaxeofpixie** [comment]
i already making aparallax-like turret,its good idea,but if you wanna write your ideas in next time,write they in pull request's.About new map,i have some ideas and maybe she is going to reality,because im not good map maker this maps will be not so soon.
