### ISSUE TITLE
118 error

### ISSUE THREAD

**Issue by DatOnePlayer** [pixaxeofpixie/Braindustry-Mod#13]
![Screenshot_20201128-092718_Mindustry](https://user-images.githubusercontent.com/61370548/100492134-2b693700-315c-11eb-8e72-4896311b8f71.jpg)
![Screenshot_20201128-092709_Mindustry](https://user-images.githubusercontent.com/61370548/100492136-2dcb9100-315c-11eb-867e-dd641e3713e8.jpg)
![Screenshot_20201128-092704_Mindustry](https://user-images.githubusercontent.com/61370548/100492139-2efcbe00-315c-11eb-9c4d-359586924ae4.jpg)
![Screenshot_20201128-092658_Mindustry](https://user-images.githubusercontent.com/61370548/100492140-302deb00-315c-11eb-9ced-4577dc62031b.jpg)

**Comment by DatOnePlayer** [comment]
@pixaxeofpixie

**Comment by pixaxeofpixie** [comment]
Thanks,i already know about that,fix be in a ~hour.

**Comment by pixaxeofpixie** [comment]
fixed
