### ISSUE TITLE
Some content have errors

### ISSUE THREAD

**Issue by DatOnePlayer** [pixaxeofpixie/Braindustry-Mod#14]
![Screenshot_20201129-163000_Mindustry](https://user-images.githubusercontent.com/61370548/100538118-4ae98800-3260-11eb-9281-7ed359c09a6a.jpg)
![Screenshot_20201129-162955_Mindustry](https://user-images.githubusercontent.com/61370548/100538119-4d4be200-3260-11eb-9fe5-74ccc1fb188e.jpg)
![Screenshot_20201129-162950_Mindustry](https://user-images.githubusercontent.com/61370548/100538122-4de47880-3260-11eb-825d-d03af8945a53.jpg)
![Screenshot_20201129-162945_Mindustry](https://user-images.githubusercontent.com/61370548/100538123-4e7d0f00-3260-11eb-936c-42551a4969d5.jpg)
![Screenshot_20201129-162940_Mindustry](https://user-images.githubusercontent.com/61370548/100538124-4f15a580-3260-11eb-8976-bdfd8ea4e16f.jpg)

**Comment by DatOnePlayer** [comment]
@pixaxeofpixie

**Comment by pixaxeofpixie** [comment]
at 120.5 no one error i dont get.
