### ISSUE TITLE
Bugs on Refigerant Reactor

### ISSUE THREAD

**Issue by DatOnePlayer** [pixaxeofpixie/Braindustry-Mod#15]
It takes thorium and the liquid but didn't produce any power or even heat
The light sprite is an Oh No
![Screenshot_20201201-220212_Mindustry](https://user-images.githubusercontent.com/61370548/100757679-3d2f3080-3421-11eb-9c22-34177b0577d7.jpg)

**Comment by DatOnePlayer** [comment]
@pixaxeofpixie

**Comment by pixaxeofpixie** [comment]
reactor produce power but this dont view in hes menu.(i test it many times)
