### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by DatOnePlayer** [pixaxeofpixie/Braindustry-Mod#2]
Do you have any discord? It might easier to contribute or suggesting

**Comment by pixaxeofpixie** [comment]
ow no.i dont create discrord for this mod but thnaks for idea!

**Comment by pixaxeofpixie** [comment]
https://discord.gg/Bm6u6M link to server

**Comment by DatOnePlayer** [comment]
Hey umm, the link is expired

**Comment by NiChrosia** [comment]
amazing
