### ISSUE TITLE
Exometal Smelter 

### ISSUE THREAD

**Issue by ddg42** [pixaxeofpixie/Braindustry-Mod#22]
![Screenshot_20201222-082444_Mindustry](https://user-images.githubusercontent.com/76484536/102898526-42373c80-442f-11eb-9b85-051a4deedf44.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain 

**Smartphone (please complete the following information):**
 S10e
121.4

**Additional context**

**Comment by pixaxeofpixie** [comment]
Oh, thanx for bug report, i try to fix it.

**Comment by pixaxeofpixie** [comment]
![Uploading Screenshot_2020-12-22-18-51-48-277_io.anuke.mindustry.jpg…]()
Fixed
