### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by ThatOneBepis** [pixaxeofpixie/Braindustry-Mod#23]
**Describe the bug**
[E] rhino.EvaluatorException: missing ) after argument list (unitAbilities#31)
from last_log.txt

**To Reproduce**
1. launch the game

**Expected behavior**
Not giving an error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version:: idek

**Additional context**
Not causing the game to crash, but it severely fiddles with gameplay

**Comment by pixaxeofpixie** [comment]
ok, i merge pull request.
