### ISSUE TITLE
I can't play the mod

### ISSUE THREAD

**Issue by DatOnePlayer** [pixaxeofpixie/Braindustry-Mod#3]
Issue : missing item name "graphenite" all of them have the same issue
![Screenshot_20200808-151934_Mindustry](https://user-images.githubusercontent.com/61370548/89705847-c6aa8680-d98a-11ea-84e4-87884844331a.jpg)

**Comment by pixaxeofpixie** [comment]
fixed

**Comment by DatOnePlayer** [comment]
Hey @pixaxeofpixie the discord link is expired mind sending them again?

**Comment by pixaxeofpixie** [comment]
ok

**Comment by pixaxeofpixie** [comment]
https://discord.gg/qzFmj8

**Comment by DatOnePlayer** [comment]
Sorry, it's expired again @pixaxeofpixie

**Comment by pixaxeofpixie** [comment]
what

**Comment by pixaxeofpixie** [comment]
https://discord.gg/WqrWKW8

**Comment by pixaxeofpixie** [comment]
endless link
