### ISSUE TITLE
hello from alexservers

### ISSUE THREAD

**Issue by alexpvpmindustry** [pixaxeofpixie/Braindustry-Mod#33]
hello,
i have come across your Braindustry-Mod and it seems cool.
i want to add this mod to my servers, for the public to play.
is it ok with you?

from,
alex (ping me in disc alex_unique_modifier#8760 ) ❤️

**Comment by pixaxeofpixie** [comment]
Okay, you can.

**Comment by alexpvpmindustry** [comment]
thank you!!! you may close this "issue".
