### ISSUE TITLE
Yours spiders have a habit of drowning

### ISSUE THREAD

**Issue by BlueWolf3682** [pixaxeofpixie/Braindustry-Mod#37]
**Describe the bug**
All the purple spider units can't walk over walls, and most drown in deep liquids.
*image with Exotic Mod's Blaze unit for comparison*
![Screenshot_20210326-120607](https://user-images.githubusercontent.com/61173114/112675038-4313ac00-8e2c-11eb-8dbc-835414c7dc97.png)

**To Reproduce**
1. Spawn a spider in deep water. 
2. Spawn a spider on land and try walking over walls.

**Expected behavior**
It will drown, and it will be stopped by the walls.

**Screenshots**
![Screenshot_20210325-154758](https://user-images.githubusercontent.com/61173114/112675212-7bb38580-8e2c-11eb-9d73-4b8d869fd725.png)

**Desktop (please complete the following information):**
 - OS: null
 - Browser: null
 - Version: null

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android 11
 - Browser: Google Chrome
 - Version: Mindustry BE 20940, mod version 1.4.2

**Additional context**
`allowLegStep: true`, `visualElevation: 75` (in hjson) to fix btw

**Comment by pixaxeofpixie** [comment]
fixed, thank you for support.
