### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ThebestkillerTBK** [pixaxeofpixie/Braindustry-Mod#41]
The mod overrides some menu buttons and setting buttons.

**Comment by pixaxeofpixie** [comment]
screenshots please
+ android/ios/pc?

**Comment by ThebestkillerTBK** [comment]
pc.the frame drops a lot
![java_B72QnGXSAZ](https://user-images.githubusercontent.com/62250232/116814843-4fa6c500-ab8d-11eb-8c2f-eb655615dce4.png)
![java_7mNXVaXEXE](https://user-images.githubusercontent.com/62250232/116814845-50d7f200-ab8d-11eb-9b4e-25b2eb73f6f8.png)

**Comment by ThebestkillerTBK** [comment]
![java_QpZynmvxB8](https://user-images.githubusercontent.com/62250232/116815071-6d285e80-ab8e-11eb-9ae5-cb521766c011.png)
![java_9SWJl1eiAo](https://user-images.githubusercontent.com/62250232/116815072-6dc0f500-ab8e-11eb-8b8a-2da619c786b9.png)

**Comment by ThebestkillerTBK** [comment]
mod used:ui-lib

**Comment by Br0ad** [comment]
Hm

**Comment by ThebestkillerTBK** [comment]
``AdvancedSettingsMenuDialog.java``
These code overrides the modded menu and settings code.
Fix for compatibility.
```
    void rebuildMenu(){
        menu.clearChildren();

        TextButton.TextButtonStyle style = Styles.cleart;

        menu.defaults().size(300f, 60f);
        menu.button("@settings.game", style, () -> visible(0));
        menu.row();
        menu.button("@settings.graphics", style, () -> visible(1));
        menu.row();
        menu.button("@settings.sound", style, () -> visible(2));
        menu.row();
        menu.button("@settings.language", style, ui.language::show);
        if(!mobile || Core.settings.getBool("keyboard")){
            menu.row();
            menu.button("@settings.controls", style, ui.controls::show);
        }

        menu.row();
        menu.button("@settings.data", style, () -> dataDialog.show());
    }```
```
private void buildDesktop(){
        container.clear();
        container.setSize(Core.graphics.getWidth(), Core.graphics.getHeight());

        float width = 230f;
        Drawable background = Styles.black6;

        container.left();
        container.add().width(Core.graphics.getWidth()/10f);
        container.table(background, t -> {
            t.defaults().width(width).height(70f);
            t.name = "buttons";

            buttons(t,
                    new Buttoni("@play", Icon.play,
                            new Buttoni("@campaign", Icon.play, () -> checkPlay(ui.planet::show)),
                            new Buttoni("@joingame", Icon.add, () -> checkPlay(ui.join::show)),
                            new Buttoni("@customgame", Icon.terrain, () -> checkPlay(ui.custom::show)),
                            new Buttoni("@loadgame", Icon.download, () -> checkPlay(ui.load::show))
                    ),
                    new Buttoni("@editor", Icon.terrain, () -> checkPlay(ui.maps::show)), steam ? new Buttoni("@workshop", Icon.book, platform::openWorkshop) : null,
                    new Buttoni("@mods", Icon.book, ui.mods::show),
                    //not enough space for this button
                    //new Buttoni("@schematics", Icon.paste, ui.schematics::show),
                    new Buttoni("@settings", Icon.settings, ui.settings::show),
                    new Buttoni("@menu.title",Icon.menu,
                            new ButtoniUnClose("@rebuild_menu",Icon.refresh,renderer::rebuild),
                            new ButtoniUnClose("@background.stiles",Icon.effect,()->{}),
                            new ButtoniUnClose("@background.screenshot",Icon.copy,renderer::takeBackgroundScreenshot)
                            ),
                    new Buttoni("@about.button", Icon.info, ui.about::show),
                    new Buttoni("@quit", Icon.exit, Core.app::exit)
            );

        }).width(width).growY();

        container.table(background, t -> {
            submenu = t;
            t.name = "submenu";
            t.color.a = 0f;
            t.top();
            t.defaults().width(width).height(70f);
            t.visible(() -> !t.getChildren().isEmpty());

        }).width(width).growY();
    }
```

**Comment by pixaxeofpixie** [comment]
stop, you have crash or seriously bugs?

**Comment by ThebestkillerTBK** [comment]
some buttons are gone and im unable to use them

**Comment by pixaxeofpixie** [comment]
what buttons, send screenshot?

**Comment by pixaxeofpixie** [comment]
screenshots when
