### ISSUE TITLE
Multiplayer with friends is not working

### ISSUE THREAD

**Issue by MasterBrazuka666** [pixaxeofpixie/Braindustry-Mod#43]
from the point that you and your friend have the same mods as you, you can play exclusively with this friend of yours but with the braindustry update I can no longer play with him using v2 with this soon to know that there is a problem connection between friends using this particular mod after all I have been playing with my friend for a long time using this mod and only after updating it was no longer possible to play multiplayer.

**Comment by pixaxeofpixie** [comment]
steam?

**Comment by MasterBrazuka666** [comment]
> steam?

Yes

**Comment by pixaxeofpixie** [comment]
Pls send crashlog/lastlog or screenshot of error

**Comment by xandau** [comment]
no crash it doesn't even load in to the season

**Comment by xandau** [comment]
i will try hosting a dedicated server and see if I can get a crash/error log for you

**Comment by pixaxeofpixie** [comment]
try now with this https://github.com/pixaxeofpixie/Braindustry-Mod/actions/runs/863309492 and send report

**Comment by Naggies** [comment]
I can't play multiplayer with my friend. I try to join them and end up getting hit with a long loading screen and a "Failed to load world data" message. We both are on V2

**Comment by pixaxeofpixie** [comment]
fixed in build 3
