### ISSUE TITLE
Startup crash with another mod

### ISSUE THREAD

**Issue by PeanutGriffin** [pixaxeofpixie/Braindustry-Mod#44]
Since v2 I have been having crashes, I've pinpointed the cause and turns out it only crashes when it and Dimension Shard mod are both enabled at the same time, It gives me the following message upon crash: 
![image](https://user-images.githubusercontent.com/56499020/117210566-82a4bf00-ae00-11eb-9d26-5ad82934de51.png)
Crash log:
[crash-report-05_06_2021_00_13_31.txt](https://github.com/pixaxeofpixie/Braindustry-Mod/files/6430290/crash-report-05_06_2021_00_13_31.txt)

**Comment by pixaxeofpixie** [comment]
Please send last-lig.txt

**Comment by PeanutGriffin** [comment]
[last_log.txt](https://github.com/pixaxeofpixie/Braindustry-Mod/files/6430388/last_log.txt)

**Comment by pixaxeofpixie** [comment]
already fixed, 2nd build with fixes will release soon
