### ISSUE TITLE
Entering a duo crashes the game

### ISSUE THREAD

**Issue by HiImBlahh** [pixaxeofpixie/Braindustry-Mod#45]
I tried it 2 times, 1 with both of my mods on and 1 with only braindustry on. both of the times they crashed. here are the .txt files i found in the folder crashes.
[crash_1620260410497.txt](https://github.com/pixaxeofpixie/Braindustry-Mod/files/6436478/crash_1620260410497.txt)
[crash_1620260253673.txt](https://github.com/pixaxeofpixie/Braindustry-Mod/files/6436480/crash_1620260253673.txt)

I'm not sure if entering other things crashes the game but when i found out it was braindustry i deleted the mod.

**Comment by stellargrand100** [comment]
Its not just duo. Entering any turret causes the game to craah.

**Comment by pixaxeofpixie** [comment]
android right?

**Comment by Zelaux** [comment]
I fixed it
