### ISSUE TITLE
Вылет игры

### ISSUE THREAD

**Issue by Kellien** [pixaxeofpixie/Braindustry-Mod#49]
Когда я пытаюсь вселится в пушку игра вылетает и приходится перезаходить подскажите, это баг, или я что то делаю не так?

**Comment by Kellien** [comment]
Я не знаю то ли это, но после экспорта ошибки вылетела игра. лагать игра
стала (загрузка увеличилась по времени и т.д) только после установки мода.

вт, 11 мая 2021 г., 21:54 PixaxeOfPixie ***@***.***>:

**Comment by pixaxeofpixie** [comment]
Я закрою эту ветку потому что у нас есть такая же, насчёт самой ошибки мы делаем все возможное чтобы ее исправить, советую подождать до первой недели июня, тогда думаю вообще все ошибки будут устранены

**Comment by Kellien** [comment]
Хорошо, я ожидал такого ответа, спасибо, что поняли буду ждать решения)

сб, 15 мая 2021 г., 15:16 PixaxeOfPixie ***@***.***>:
