### ISSUE TITLE
Mod Crashing(Android)

### ISSUE THREAD

**Issue by SageMoisan** [pixaxeofpixie/Braindustry-Mod#52]
Everytime I open the game while trying to use the mod it crashes instantly.

**Comment by pankiwi** [comment]
pixaxeoofpixie  need crash log fix your problem

**Comment by pixaxeofpixie** [comment]
crash log

**Comment by pixaxeofpixie** [comment]
last log when
we cant fix this without data about crash

**Comment by pixaxeofpixie** [comment]
2 gb ram?

**Comment by FixArt** [comment]
Seems that braindustry conflict horiton mod.

**Comment by FixArt** [comment]
Horiton mod(not newhorizonmod) conflict with braindustry.
