### ISSUE TITLE
Other mods js is not loading

### ISSUE THREAD

**Issue by souvikpodder** [pixaxeofpixie/Braindustry-Mod#53]
Other mods JS is not loading when using **v2-beta Build 2**
But when using **2.0 Update PC ONLY STABLE** it's working fine.
Can you please fix this. If you need anything please ask.
I tried taking a build with latest code in Intellij same problem.
I am using Mindustry Version 126.2

**Comment by pixaxeofpixie** [comment]
Thx for report, we alresdy know abot this and have trying to fix this

**Comment by Zelaux** [comment]
I fixed it
