### ISSUE TITLE
Can't load multiplayer

### ISSUE THREAD

**Issue by codenamenui** [pixaxeofpixie/Braindustry-Mod#54]
Multiplayer is not working. Trying to join my friend displays an error saying "Failed to load world data!".

1. Host a game of mindustry with the mod braindustry.
2. Friend try to join the server in the local servers.
3. Connects for a while then displays the error.

I expected to load into the game properly and play with my friend with mods.

![image](https://user-images.githubusercontent.com/71966332/118434985-94476a00-b710-11eb-833e-ebb62517dab2.png)

**Desktop (please complete the following information):**
 - OS: PC
 - Version Mindustry build 126.2
 - Version Braindustry v2-beta Build 2

**Additional context**
We use zerotier one to make servers without port forwarding by making our IP the same. I did try it without zerotier by launching 2 mindustry instances to no avail.

**Comment by Zelaux** [comment]
I already know about this error. And I am looking for a way to solve this problem.
