### ISSUE TITLE
Cant play some map

### ISSUE THREAD

**Issue by qwokqwok** [pixaxeofpixie/Braindustry-Mod#55]
**Describe the bug**
I cant play on osore world

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [oppo a3s]

**Additional context**
I can play on basic world but cant play on other world

**Comment by qwokqwok** [comment]
Please help

**Comment by pixaxeofpixie** [comment]
i dont understand anything in this issue
