### ISSUE TITLE
Don't compatible with ui mods (disable all the ui from other mods).

### ISSUE THREAD

**Issue by NXE212** [pixaxeofpixie/Braindustry-Mod#56]

**Comment by pixaxeofpixie** [comment]
screenshot

**Comment by NXE212** [comment]
Before: 
![image](https://user-images.githubusercontent.com/69082491/119216391-a56fec80-bafd-11eb-8f35-008fe5759b88.png)

![image](https://user-images.githubusercontent.com/69082491/119216308-3befde00-bafd-11eb-8bf9-24c3db47ebda.png)
After: 
![image](https://user-images.githubusercontent.com/69082491/119216420-c6384200-bafd-11eb-9bc2-38cd8867f921.png)

![image](https://user-images.githubusercontent.com/69082491/119216350-6f326d00-bafd-11eb-9738-33f58a659bb6.png)

**Comment by NXE212** [comment]
I know the time at bottom right doesn't follow the order but it was me being dumb and forgot to take the mod list screenshot.

**Comment by ThebestkillerTBK** [comment]
This mod overrides too many classes and disables javascript.

**Comment by pixaxeofpixie** [comment]
try this https://github.com/pixaxeofpixie/Braindustry-Mod/actions/runs/863309492

maybe work

**Comment by NXE212** [comment]
It does work.

**Comment by NXE212** [comment]
Wait nvm the mods don't show up anything of it
![image](https://user-images.githubusercontent.com/69082491/119253032-7169f980-bbd9-11eb-88df-8726eb65d07d.png)

**Comment by pixaxeofpixie** [comment]
What mods you use with UI?

**Comment by pixaxeofpixie** [comment]
fixed in build 3
