### ISSUE TITLE
Braindustry Turret Bug (Android)

### ISSUE THREAD

**Issue by PoiiZoner3** [pixaxeofpixie/Braindustry-Mod#57]
Every time I go to control any turret, modded or not, it just crashes the game instead. I have around 10 mods installed and I went through and re-enabled each one and tested it and it's Braindustry doing it.

Mindustry version: 126.2
Samsung S9+ (Android) version 9

**Comment by pixaxeofpixie** [comment]
try this build https://github.com/pixaxeofpixie/Braindustry-Mod/actions/runs/863309492

**Comment by pixaxeofpixie** [comment]
and what now?

**Comment by PoiiZoner3** [comment]
Sorry, I never check my email

I have no idea what I'm supposed to do with that sadly so I couldn't tell
you if it works or not

**Comment by pixaxeofpixie** [comment]
Fixed in new builds, wait for new release
