### ISSUE TITLE
Can't play on sector melting point

### ISSUE THREAD

**Issue by qwokqwok** [pixaxeofpixie/Braindustry-Mod#58]
![Screenshot_2021-05-22-04-58-38-53](https://user-images.githubusercontent.com/84488314/119202274-a16eab00-baba-11eb-9e8e-cbeb1155e242.png)

**Comment by qwokqwok** [comment]
This sector has unlock but i cant play on this sector

**Comment by qwokqwok** [comment]
Helo

**Comment by qwokqwok** [comment]
Help

**Comment by pixaxeofpixie** [comment]
first you must land on the space port

**Comment by pixaxeofpixie** [comment]
not at melting point

**Comment by pixaxeofpixie** [comment]
we already fix it at new builds just wait the new release
