### ISSUE TITLE
Hello there! It is impossible to get chlorophilum Bar and I need to Crafting de reactor 

### ISSUE THREAD

**Issue by GuiVcente** [pixaxeofpixie/Braindustry-Mod#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pixaxeofpixie** [comment]
Just kill TX unit on Shnrin maps
