### ISSUE TITLE
game crash when launching to Space Port on Osore

### ISSUE THREAD

**Issue by xorblo-doitus** [pixaxeofpixie/Braindustry-Mod#62]
Playing on a 64bit Windows 10.
I use a save started without the mod.

crash log :
[crash-report-06_01_2021_18_45_30.txt](https://github.com/pixaxeofpixie/Braindustry-Mod/files/6577813/crash-report-06_01_2021_18_45_30.txt)

**Comment by pixaxeofpixie** [comment]
hello, try with this build now https://github.com/pixaxeofpixie/Braindustry-Mod/actions/runs/897317634

**Comment by pixaxeofpixie** [comment]
update mod now
