### ISSUE TITLE
I can't progress in the campaign.

### ISSUE THREAD

**Issue by CrispedBread** [pixaxeofpixie/Braindustry-Mod#67]
I think Polar Rift is the place I need to go to next, because that will unlock Hyper Multiplicative Reconstructor, but its nowhere on any of the planets. In the core database It says I have it completed but I have not captured it nor can I see it anywhere. I have captured every single named sector there is, and finished everything in the tech tree that I can. I've attached screenshots of the planets. I'm also not sure if this is a bug or if the mod is just not finished yet. Either way my friend and I are loving the mod so far. 
![20210607031310_1](https://user-images.githubusercontent.com/85488883/121000158-beec7780-c73e-11eb-8fbd-ea0b864ef5c5.jpg)
![20210607031247_1](https://user-images.githubusercontent.com/85488883/121000174-c449c200-c73e-11eb-945e-67d9a2e4f456.jpg)
![20210607031239_1](https://user-images.githubusercontent.com/85488883/121000178-c57aef00-c73e-11eb-856b-9a1ca8b391b5.jpg)
![20210607031229_1](https://user-images.githubusercontent.com/85488883/121000183-c6ac1c00-c73e-11eb-8fc2-1969ec185d6d.jpg)
![20210607031208_1](https://user-images.githubusercontent.com/85488883/121000198-ca3fa300-c73e-11eb-9f8a-00ceb0ae618c.jpg)

**Comment by pixaxeofpixie** [comment]
Polar Rift is the Map on Osore

You must capture Space Port(unlocked after capture of planetary terminal and unlock of intr. accelerator) -> 451F(spark, captured space port) -> meltingPoint(hyperMultiplicativeReconstructor and captured 451f) -> magmatic Electrostation(meltingPoint + magmaGenerator) -> Polar Rift

**Comment by Kryvytsky** [comment]
![Screenshot_20210608_000107](https://user-images.githubusercontent.com/81460407/121088147-f9611d80-c7ed-11eb-84c4-12869797fac5.jpg)
![Screenshot_20210608_000145](https://user-images.githubusercontent.com/81460407/121088165-ffef9500-c7ed-11eb-9bd0-246c5f456bce.jpg)
I tried this mod on campaign, but it still bugged. Third planet unlock four sectors in tech tree, but actually I can deploy on three sectors already on start.

**Comment by CrispedBread** [comment]
> Polar Rift is the Map on Osore
> 
> You must capture Space Port(unlocked after capture of planetary terminal and unlock of intr. accelerator) -> 451F(spark, captured space port) -> meltingPoint(hyperMultiplicativeReconstructor and captured 451f) -> magmatic Electrostation(meltingPoint + magmaGenerator) -> Polar Rift

I have captured 451F, and melting point requires me to research hyper multiplicative reconstructor, but in order to research what i assume is the hyper multiplicative reconstructor, I need to capture polar rift. If this isnt the hyper multiplicative reconstructor, then I dont know what is, its nowhere on the tech tree. 

![20210607174641_1](https://user-images.githubusercontent.com/85488883/121105284-ade04c80-c7b8-11eb-8c5c-93dc39c351b5.jpg)

**Comment by pixaxeofpixie** [comment]
try this build https://github.com/pixaxeofpixie/Braindustry-Mod/actions/runs/919397200

(download "Braindustry-Mod" file)

**Comment by CrispedBread** [comment]
That fixed it I believe. Melting point no longer requires the Hyper Multiplicative Reconstructor, so I can go there freely. Thanks!
