### ISSUE TITLE
Can't do polar rift

### ISSUE THREAD

**Issue by bjones70** [pixaxeofpixie/Braindustry-Mod#68]
#67 pretty much same problem as this last bug report.  My tech tree says polar rift is complete, but I am unable to visit that zone.  There was some kind of download provided for #67, but I couldn't figure out how to use it.

**Comment by bjones70** [comment]
![Screenshot_20210608-214648_Mindustry](https://user-images.githubusercontent.com/85626747/121575603-30e9e880-c9ed-11eb-97e1-7dcd1543e7fb.jpg)
I think that is where polar rift is supposed to be

**Comment by pixaxeofpixie** [comment]
try last build
