### ISSUE TITLE
I can't find the resources on the tech tree

### ISSUE THREAD

**Issue by DatOnePlayer** [pixaxeofpixie/Braindustry-Mod#7]
I unlocked the buildings for creating them (Odinium and Graphenite) but I didn't see their resources on the tech tree, help?

**Comment by DatOnePlayer** [comment]
@pixaxeofpixie

**Comment by pixaxeofpixie** [comment]
hm,i dont test mod t the campaign,im try to fix that on a few days,but i think its not a mod problem,maybe this happen because Mindsutry 6.0 i still beta and anuke dont can prepare all for modding,but im try to fix that.

**Comment by pixaxeofpixie** [comment]
try now,maybe its work
