### ISSUE TITLE
Osore campaign sectors have no enemies, capture immediately

### ISSUE THREAD

**Issue by adamsong** [pixaxeofpixie/Braindustry-Mod#72]
**Describe the bug**
Launching to a campaign sector on Osore results in the sector capturing immediately. This did not occur on Space port or random sectors.

**To Reproduce**
1. Launch to a campaign sector on Osore
2. Win

**Expected behavior**
There should be waves of enemies to fight.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.0 Public Beta

**Comment by pixaxeofpixie** [comment]
I still cannot understand what this error is connected with, the fix will probably be released after July 14-16, wait for updates, and if you can, please send the last log

**Comment by pixaxeofpixie** [comment]
i really dont know how to fix this

**Comment by Davidvaslk** [comment]
you are lucky to me or let me go to osores or any other planet, try activating the cheats and go to change rules and activate waves
