### ISSUE TITLE
with the included mod the game does not start

### ISSUE THREAD

**Issue by ilya034** [pixaxeofpixie/Braindustry-Mod#73]
with the included mod the game does not start
the mod was downloaded from the modification browser right before bug

everything else is here:
[crash-report-07_14_2021_22_29_49.txt](https://github.com/pixaxeofpixie/Braindustry-Mod/files/6817969/crash-report-07_14_2021_22_29_49.txt)

**Comment by Zelaux** [comment]
bug fixed install new version
