### ISSUE TITLE
gas blocks

### ISSUE THREAD

**Issue by Dude-324** [pixaxeofpixie/Braindustry-Mod#76]
**Describe the bug**
placing gas related blocks crashed the game
**To Reproduce**
enter a game and place a gas conduit a gas router or a gas tank
**Expected behavior**
the gas conduit/router/tank to be placed
**Screenshots**
[2021-07-23 13-55-24.zip](https://github.com/pixaxeofpixie/Braindustry-Mod/files/6870448/2021-07-23.13-55-24.zip)
^^^this is a video of me placing the gas conduit
![image](https://user-images.githubusercontent.com/71083621/126822358-7c481bbe-ed37-41ef-b74d-6440d38ed743.png)
^^an image of what comes up after the crash
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10
 - Version [e.g. 22] 128

**Smartphone (please complete the following information):**

**Additional context**
this seems to happen with any block which has gas capacity. i saw it first with the gas router but the methane burner and black hole reactor also crash the game, im assuming that all block which have gas capacity crash the game

**Comment by Zelaux** [comment]
already fixed, wait for new release please
