### ISSUE TITLE
No jump/start buttons (that must be appear in right side) in campaign for new planet (Android)

### ISSUE THREAD

**Issue by Lordkot** [pixaxeofpixie/Braindustry-Mod#77]
No jump/start buttons (that must be appear in right side) in campaign for new planet (Android)

Pre-alpha build 128.1
Android

Issue can be see on attached screenshoots 
![20210728_234741](https://user-images.githubusercontent.com/87755804/127449734-92d6f3a1-3e57-42b6-a0a5-7ef468482724.jpg)
![20210728_234812](https://user-images.githubusercontent.com/87755804/127449740-2c869a4e-8ea3-474f-9cb9-ef8935d5c8d8.jpg)
![20210728_234837](https://user-images.githubusercontent.com/87755804/127449749-6050a5ed-f4d6-48e4-bf77-11f7a7ae51f2.jpg)
![20210728_234909](https://user-images.githubusercontent.com/87755804/127449767-74d4f9f3-30da-4c78-8c4c-d13430c14390.jpg)

Thank you

**Comment by Tareth** [comment]
I have the same problem on Windows 8. 

Setup tested - 
Mindustry 128.1 
Mindustry 129.1 - 32 bit
Mindustry 129.1 - 64 bit

Clean slate save, [erased save data, erased research etc]

Another mods - Time Control [ Did not test without that mod, doubt it can conflict, you never know ] 


As shown on the OP issue, i also have no option to send myself to the other planet, although, i am not sure why. 
When unlocking Planetary Terminal Launch, and completing the last map of base game, SpacePort automatically completes without unlocking the planets. I checked with UnlockMode, and even enabling planets manually does not help. 

I have very little expirience with modding/coding so i doubt i can find the cause myself.

**Comment by Zelaux** [comment]
fixed
