### ISSUE TITLE
no way to get to the new planets

### ISSUE THREAD

**Issue by Elisedlund** [pixaxeofpixie/Braindustry-Mod#79]
Have built the interplanetary accelerator which is suggesting me to go to the other planets.

in the planet map I can see other planets in the background but I have no way of selecting them or traveling to them 

using the latest steam beta build 129.2 (v7)
there is now way to rollback to an older older version in steam. 
the release version v6 is incompatible with this mod.

**Comment by Zelaux** [comment]
The first one is already in [issues](pixaxeofpixie/Braindustry-Mod/issues/77)
Second, it is fixed, wait for the release of the new version
