### ISSUE TITLE
Mod error

### ISSUE THREAD

**Issue by Aweguy** [pixaxeofpixie/Braindustry-Mod#8]
The last update changed how material unlocking works. Well this has caused some problems to my  save as it crashes without your mod (I think). So I cannot play without it. As shown in the picture that's the error. 
![Screenshot_20201117-153920](https://user-images.githubusercontent.com/60873527/99397701-14b91980-28ec-11eb-8457-24a8222be98b.jpg)

**Comment by DatOnePlayer** [comment]
Same with me

**Comment by DatOnePlayer** [comment]
@pixaxeofpixie

**Comment by Aweguy** [comment]
I made it work without losing my tech by resetting my campaign bases. For me, not a big deal since I had just restarted at ground zero.

**Comment by DatOnePlayer** [comment]
That is painful to do, I have thousands of resources already....

**Comment by Aweguy** [comment]
Oh god... Bad for you. Seems we must wait for pixaxe

**Comment by Aweguy** [comment]
Well the fix can be very easy if on pc. You just change the research requirements for the affected item. I could even push the fix, but I am on phone and it's a bit harder to change files on it.

**Comment by pixaxeofpixie** [comment]
f#ck
okay im try fix it at hour

**Comment by pixaxeofpixie** [comment]
try now
**_now plastic need to be research after exo alloy._**

**Comment by pixaxeofpixie** [comment]
> Well the fix can be very easy if on pc. You just change the research requirements for the affected item. I could even push the fix, but I am on phone and it's a bit harder to change files on it. Also I don't know where Pixeaxe would like the plastic tech placed.
> 
> research: plastanium
> 
> This line should change in the plastic hjson to anything else until he fixes it.

im wanted to player research plastic after plastanium,but mindustry dont think.

**Comment by pixaxeofpixie** [comment]
> That is painful to do, I have thousands of resources already....

hm,its strange.
I didn't know that after errors the resources are destroyed in the campaign

**Comment by DatOnePlayer** [comment]
@pixaxeofpixie not like that, when I restarted the campaign I lost the resources not because of the error

**Comment by Aweguy** [comment]
The bug is now fixed. Ty.
