### ISSUE TITLE
Does not let me enter the other planets

### ISSUE THREAD

**Issue by Davidvaslk** [pixaxeofpixie/Braindustry-Mod#80]
My problem is that when I play in the campaign with the mod and I unlock the interplanetary accelerator and the space port, the game does not let me enter the other planets, the button to change planet simply does not appear and therefore I do not enjoy the mod at all.

by the way i am on pc windows 10 64 bits

**Comment by Davidvaslk** [comment]
I also wanted to advise that the mod download it from the game mods search engine, is there a problem with that?

**Comment by Zelaux** [comment]
Take a look [here](https://github.com/pixaxeofpixie/Braindustry-Mod/issues/79)
(just a screenshot)
![image](https://user-images.githubusercontent.com/58040045/131234702-1274cd63-c156-442a-a318-b121a5ea558f.png)
