### ISSUE TITLE
hello game crashes on loading screen ||||Android game version 135 unstable alpha device Poco xs pro 

### ISSUE THREAD

**Issue by YUKiCHANZxc** [pixaxeofpixie/Braindustry-Mod#92]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheGamer1002** [comment]
![13E705CA-D82A-49BB-AE21-6A7B9581013D](https://user-images.githubusercontent.com/48131223/155401098-399b4cb4-583f-4ed4-96c3-4c6a2be17f3c.jpeg)
