### ISSUE TITLE
can't get on another planet

### ISSUE THREAD

**Issue by MaximIce1** [pixaxeofpixie/Braindustry-Mod#93]
Win10, Mindustry build: Steam 135; mod build: 2.0.1.3
after activating interplanetary accelerator space port was unlock avomatically
but in sector select no jump buttons to other planets

![image](https://user-images.githubusercontent.com/79106345/162612939-abd95142-32f6-4ea4-8d86-85c909bfeaa7.png)
![image](https://user-images.githubusercontent.com/79106345/162613032-5351d4bb-14f6-4e73-915a-26c201c76dca.png)

manual unlock doesn't help

**Comment by nikitax44** [comment]
i have the same problem
