### ISSUE TITLE
Won't Load On Server

### ISSUE THREAD

**Issue by phaze-the-dumb** [pixaxeofpixie/Braindustry-Mod#94]
**Describe the bug**
When I start the server I get an error and the game crashes, I noticed there was another issue with the same error but it says it was fixed

**To Reproduce**
1. Downloaded the mod into the servers mods folder
2. Started the server

**Expected behavior**
The Server To Load

**Screenshots**
![image](https://user-images.githubusercontent.com/57566773/169612338-6e9052b9-6785-4dd2-b91c-6f25570aafee.png)

**Desktop (please complete the following information):**
 - OS:  Ubuntu
 - Version: Server, version 21 i think

[EDIT] The mindustry version is 135 (v7)

**Comment by pixaxeofpixie** [comment]
братан мод сдох зачем ты эти issues открываешь
